import 'bootstrap/dist/css/bootstrap.min.css'
import 'font-awesome/css/font-awesome.min.css'
import 'animate.css'
import 'react-toastify/dist/ReactToastify.css'
import './inspinia.css'
import './custom.css'
